export default {
  // PRIMARY = '#1779ba';
  // export const SECONDARY = '#767676';
  // export const WHITE = '#FFFFFF';
  // export const BLACK = '#000000';

  // // ACTIONS
  // export const SUCCESS = '#3adb76';
  // export const WARNING = '#ffae00';
  // export const ALERT = '#cc4b37';

  // // GRAYSCALE
  // export const GRAY_LIGHT = '#e6e6e6';
  // export const GRAY_MEDIUM = '#cacaca';
  // export const GRAY_DARK = '#8a8a8a';

  BACKGROUND_COLOR_LIGHT: '#ffe5d9',
  BACKGROUND_COLOR: '#4F518C',
  NAVIGATION_BAR_BACKGROUND_COLOR: '#2C2A4A',
  ACCENT_COLOR: '#DABFFF',
  BOX_SHADOW_COLOR: 'black',
  BORDER_COLOR_LIGHT: 'gray',
  BORDER_COLOR_DARK: '#907AD6',
  MODAL_OVERLAY_COLOR: 'rgba(0,0,0,0.7)',
  ROUNDED_BUTTON_COLOR: '#FCA311',
  ROUNDED_BUTTON_COLOR_DISABLED: '#80798A',
  ROUNDED_BUTTON_TEXT: 'white',
  TEXT_BUTTON_COLOR: 'white',
  SWITCH_TRACK_DISABLED_COLOR: '#767577',
  SWITCH_TRACK_ENABLED_COLOR: '#FCA311',
  SWITCH_THUMB_DISABLED_COLOR: '#008bdb',
  SWITCH_THUMB_ENABLED_COLOR: 'white',
  CONTACT_ICON_FACEBOOK: '#4267B2',
  CONTACT_ICON_INSTAGRAM: '#C13584',
  CONTACT_ICON_PHONE: '#25D366',
  CONTACT_ICON_DISABLED: 'gray',
  INPUT_FIELD_ACTIVE: 'white',
  INPUT_FIELD_INACTIVE: '#80798A',
  INPUT_FIELD_TEXT: 'white',
};
